resources:
- name: docker-images
  type: git
  source:
    uri: https://github.com/ECSTeam/docker-images.git
    branch: ubuntu-fix

jobs:
- name: test-docker-image
  public: true
  plan:
  - get: docker-images
  - task: run
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: {{docker-repo}}
          tag: 1.1
      inputs:
      - name: docker-images
      run:
        path: docker-images/ci/scripts/test-docker.sh
