resources:
- name: docker-images
  type: git
  source:
    uri: https://github.com/ECSTeam/docker-images.git
    branch: build-verify
#    username: ((git-svc-user))
#    password: ((git-svc-token))

#- name: version
#  type: semver
#  source:
#    initial_version: 1.0.0
#    driver: s3
#    bucket: ((s3_bucket))
#    key: ((s3_semver_key))
#    access_key_id: ((access_key_id))
#    secret_access_key: ((secret_access_key))
#    region_name: ((s3_region))

- name: concourse-ubuntu-latest-rc
  type: docker-image
  source:
#    email: ((docker-hub-email))
    username: ((docker-hub-user))
    password: ((docker-hub-password))
    repository: {{docker-hub-repo}}
    tag: latest-rc
- name: concourse-ubuntu-latest
  type: docker-image
  source:
#    email: ((docker-hub-email))
    username: ((docker-hub-user))
    password: ((docker-hub-password))
    repository: {{docker-hub-repo}}
    tag: latest

jobs:
- name: build-concourse-latest-rc
  public: true
  plan:
  - get: docker-images
#  - put: version
#    params: {bump: minor}
  - put: concourse-ubuntu
    params:
      build: docker-images/concourse-ubuntu
#      tag: version/version
- name: test-docker-image
  public: true
  plan:
  - get: docker-images
    passed: build-concourse-latest-rc
  - task: run
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: {{docker-hub-repo}}
          tag: latest-rc
      inputs:
      - name: docker-images
      run:
        path: docker-images/ci/scripts/test-docker.sh
- name: push-concourse-latest
  public: true
  plan:
  - get: concourse-ubuntu-latest-rc
    passed: test-docker-image
    params: { save: true }
  - put: concourse-ubuntu-latest
    params:
      load: concourse-ubuntu-latest-rc
