---
groups:
  - name: docker-build
    jobs:
      - 'build-docker-latest-rc'
      - 'test-docker-image'
      - 'push-docker-latest'
      - 'verify-docker-version'

resources:
- name: version
  type: semver
  source:
    initial_version: 0.0.0
    driver: git
    uri: ((git-repo-ssh))
    branch: version
    file: ((docker-image-name))-version
    private_key: ((git-svc-user-private-key))
- name: dockerversion
  type: git
  source:
    uri: ((git-repo-public))
    branch: version
- name: docker-files-git
  type: git
  source:
    uri: ((git-repo-public))
    branch: semver
    paths:
      - ((git-folder))

- name: docker-git
  type: git
  source:
    uri: ((git-repo-public))
    branch: semver

- name: ((docker-image-name))-docker-latest-rc
  type: docker-image
  source:
    username: ((docker-hub-user))
    password: ((docker-hub-password))
    repository: ((docker-hub-repo))
    tag: latest-rc
- name: ((docker-image-name))-docker-latest
  type: docker-image
  source:
    username: ((docker-hub-user))
    password: ((docker-hub-password))
    repository: ((docker-hub-repo))
    tag: latest

jobs:
- name: build-docker-latest-rc
  public: true
  plan:
  - put: version
    params: {bump: patch}
  - get: dockerversion
  - get: docker-files-git
    trigger: true
  - put: ((docker-image-name))-docker-latest-rc
    params:
      build: docker-files-git/((git-folder))
- name: test-docker-image
  public: true
  plan:
  - get: docker-git
  - get: ((docker-image-name))-docker-latest-rc
    passed: ['build-docker-latest-rc']
    trigger: true
  - task: run
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ((docker-hub-repo))
          tag: latest-rc
      inputs:
      - name: docker-git
      run:
        path: docker-git/ci/scripts/test-docker.sh
- name: push-docker-latest
  public: true
  plan:
  - get: ((docker-image-name))-docker-latest-rc
    passed: ['test-docker-image']
    trigger: true
    params: { save: true }
  - put: ((docker-image-name))-docker-latest
    params:
      load: ((docker-image-name))-docker-latest-rc
- name: verify-docker-version
  public: true
  plan:
  - get: docker-git
  - get: dockerversion
  - get: ((docker-image-name))-docker-latest
    passed: ['push-docker-latest']
    trigger: true
  - task: run
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ((docker-hub-repo))
          tag: latest
      inputs:
      - name: docker-git
      - name: dockerversion
      run:
        path: docker-git/ci/scripts/verify-docker-version.sh
