resources:
- name: docker-images
  type: git
  source:
    uri: https://github.com/ECSTeam/docker-images.git
    branch: master
    username: ((git-svc-user))
    password: ((git-svc-token))

#- name: version
#  type: semver
#  source:
#    initial_version: 1.0.0
#    driver: s3
#    bucket: ((s3_bucket))
#    key: ((s3_semver_key))
#    access_key_id: ((access_key_id))
#    secret_access_key: ((secret_access_key))
#    region_name: ((s3_region))

- name: concourse-ubuntu
  type: docker-image
  source:
#    email: ((docker-hub-email))
    username: ((docker-hub-user))
    password: ((docker-hub-password))
    repository: cgicloudnative/concourse-ubuntu
    tag: 1.0.0

jobs:
- name: publish
  public: true
  plan:
  - get: docker-images
#  - put: version
#    params: {bump: minor}
  - put: concourse-ubuntu
    params:
      build: docker-images/concourse-ubuntu
#      tag: version/version
#  - task: run
#    config:
#      platform: linux
#      image_resource:
#        type: docker-image
#        source:
#          repository: ((docker-hub-username))/concourse-tutorial-hello-world
#      run:
#        path: /bin/hello-world
#        args: []
#      params:
#        NAME: ((docker-hub-username))
