---
groups:
  - name: concourse
    jobs:
      - 'build-concourse-latest-rc'
      - 'test-docker-image'
      - 'push-concourse-latest'

resources:
- name: docker-images
  type: git
  source:
    uri: https://github.com/ECSTeam/docker-images.git
    branch: master
    paths:
      - concourse-ubuntu


- name: docker-latest-rc
  type: docker-image
  source:
    username: ((docker-hub-user))
    password: ((docker-hub-password))
    repository: {{docker-hub-repo}}
    tag: latest-rc
- name: docker-latest
  type: docker-image
  source:
    username: ((docker-hub-user))
    password: ((docker-hub-password))
    repository: {{docker-hub-repo}}
    tag: latest

jobs:
- name: build-docker-latest-rc
  public: true
  plan:
  - get: docker-images
    trigger: true
  - put: docker-latest-rc
    params:
      build: docker-images/concourse-ubuntu
- name: test-docker-image
  public: true
  plan:
  - get: docker-images
  - get: docker-latest-rc
    passed: ['build-docker-latest-rc']
    trigger: true

  - task: run
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: {{docker-hub-repo}}
          tag: latest-rc
      inputs:
      - name: docker-images
      run:
        path: docker-images/ci/scripts/test-docker.sh
- name: push-docker-latest
  public: true
  plan:
  - get: build-docker-latest-rc
    passed: ['test-docker-image']
    trigger: true
    params: { save: true }
  - put: docker-latest
    params:
      load: docker-latest-rc
